apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-node-test-deployment
  labels:
    app: nginx-node-test-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-node-test-deployment
  template:
    metadata:
      labels:
        app: nginx-node-test-deployment
    spec:
      containers:
        - name: nginx-node-test
          image: tar3kom/nginx-node-test:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-node-test-service
spec:
  type: NodePort
  selector:
    app: nginx-node-test-service
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000 # หรือจะลบออกให้ระบบเลือกเองก็ได้
